---
title: "caribouRSF"
author: "tmichele"
date: "27 February 2019"
output: pdf_document
---

# Overview

From the ECCC 2011:

6.2.4 Taiga Plains
Several coefficients had confounding effects when modelled together in the Taiga Plains
ecozone model. Due to these issues, peatlands and NDVI were not included in the model. In
general, caribou selected for moderate elevations of ~620 m, as well as intermediate values of
ruggedness and for herbaceous landcover types in relationship to the constant (Table 46).
Caribou exhibited avoidance of high road density (Figure 45), deciduous, shrub and water
landcover types. In contrast to the other ecozone models, caribou in Taiga Plains avoided both
recent and old burns (Figure 47). However, the Taiga Plains model poorly predicted withheld
caribou locations (rs = 0.13) and also had relatively low model accuracy (ROC = 0.60) and a
low pseudo R2 (Table 44, 45).

Table 46. Estimates of caribou selectivity (β) coefficients and standard errors (SE) at the ecozone level from generalized linear mixed models with
a random intercept for individual caribou. Boreal woodland caribou telemetry datasets were collected across Canada between 2000 and 2010 by
provinces and territories. Positive selectivity coefficients indicate selection for that covariate and negative selectivity coefficients indicate
avoidance. Squared terms (such as elevation2) indicate that the relationship was quadratic (i.e., caribou selected for intermediate elevations).

presenseProbability ~ Intercept + elevation + elevation^2 + vrug + vrug^2 + roadDensity + Deciduous + Shrub + Herb + Water + RecentBurn + OldBurn
"presenseProbability ~ Intercept + elevation + elevation^2 + vrug + vrug^2 + roadDensity + Deciduous + Shrub + Herb + Water + RecentBurn + OldBurn"


elevation.url <- "https://drive.google.com/open?id=1P4grDYDffVyVXvMjM-RwzpuH1deZuvL3" # Has more layers than that
elevation <- "topoStack.zip"

vrug.url <- "https://drive.google.com/open?id=16u07GpGQbBd5Yh8xPZ_xLiUo31OF0uDP"
vrug.fileName <- "vrug_bcr6.zip"

roadDensity.url <- ""
roadDensityName <- ""

water.url <- "https://drive.google.com/open?id=1YVTcIexNk-obATw2ahrgxA6uvIlr-6xm"
waterName <- "wetlandsNWT250m.tif" # This could also potentially be generated using functions (as I did for birds). Or come from birds Model. THis migh be just for .inputObjs

shrub, herb <- LCC05 # exists 

recentBurn <- scfm same way for the other caribou model... < 40
oldBurn <- scfm same way for the other caribou model... > 40

# Usage

```{r module_usage}
# Load SpaDES
library("SpaDES")
library("raster")

dayOfRecording <- today <- toupper(format(Sys.time(), "%d%b%y"))

isTEST <- TRUE

if (isTEST){
    dayOfRecording <- "14MAR19"
}

# Source functions in R folder
invisible(sapply(X = list.files(file.path(getwd(), "R"), full.names = TRUE), FUN = source))

# Set a storage project folder
workDirectory <- getwd()
message("Your current temporary directory is ", tempdir())

checkInputPath <- tryCatch(checkPath(file.path(dirname(dirname(getwd())), "outputs", dayOfRecording)), error = function(e) NULL)
if (is.null(checkInputPath)){
  inpPath <- tempdir()
} else {
  inpPath <- checkInputPath
}

checkOutputPath <- tryCatch(checkPath(file.path(dirname(dirname(getwd())), "outputs", today)), error = function(e) NULL)
if (is.null(checkOutputPath)){
  outPath <- tempdir()
} else {
  outPath <- checkOutputPath
}

setPaths(modulePath = file.path(dirname(getwd())), 
         inputPath = inpPath, outputPath = outPath)
getPaths() # shows where the 4 relevant paths are

times <- list(start = 0, end = 4)

parameters <- list(
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("caribouPopGrowthModel")
.objects <- list()
inputs <- list()
outputs <- list()

if (quickPlot::isRstudioServer()) options(httr_oob_default = TRUE)

caribousRSF <- simInitAndSpades(times = times, params = parameters, modules = modules,
                 objects = .objects)

```
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("caribouRSF", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

